-- =====================================================================
-- Refonte site SIO - Structure de la base de données
-- Cible : PostgreSQL 12+
-- Fichier : schema_sio.sql
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Nettoyage (à commenter si vous ne voulez pas écraser l'existant)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS logs            CASCADE;
DROP TABLE IF EXISTS galerie_photos  CASCADE;
DROP TABLE IF EXISTS articles        CASCADE;
DROP TABLE IF EXISTS liens           CASCADE;
DROP TABLE IF EXISTS fichiers        CASCADE;
DROP TABLE IF EXISTS inscriptions    CASCADE;
DROP TABLE IF EXISTS users           CASCADE;
DROP TABLE IF EXISTS role            CASCADE;
DROP FUNCTION IF EXISTS set_updated_at() CASCADE;

-- ---------------------------------------------------------------------
-- Table : role
-- ---------------------------------------------------------------------
CREATE TABLE role (
    role_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_role  varchar(50) NOT NULL UNIQUE
);

COMMENT ON TABLE role IS 'Rôles applicatifs (admin, professeur, etudiant...)';

-- ---------------------------------------------------------------------
-- Table : users
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id_users       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_users    varchar(50)  NOT NULL UNIQUE,
    password_hash  varchar(255) NOT NULL,
    nom            varchar(100) NOT NULL,
    prenom         varchar(100) NOT NULL,
    email          varchar(255) NOT NULL UNIQUE,
    role_id        integer      NOT NULL,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES role (role_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX idx_users_role_id ON users (role_id);

COMMENT ON COLUMN users.password_hash IS 'Hash du mot de passe (bcrypt / argon2) - jamais en clair';

-- ---------------------------------------------------------------------
-- Table : inscriptions
-- ---------------------------------------------------------------------
CREATE TABLE inscriptions (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom        varchar(100) NOT NULL,
    prenom     varchar(100) NOT NULL,
    email      varchar(255) NOT NULL,
    telephone  varchar(20),
    message    text,
    statut     varchar(20)  NOT NULL DEFAULT 'en_attente',
    notifie    boolean      NOT NULL DEFAULT false,
    created_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT chk_inscriptions_statut
        CHECK (statut IN ('en_attente', 'acceptee', 'refusee'))
);

CREATE INDEX idx_inscriptions_statut ON inscriptions (statut);

COMMENT ON COLUMN inscriptions.statut  IS 'en_attente / acceptee / refusee';
COMMENT ON COLUMN inscriptions.notifie IS 'Notification envoyée aux professeurs';

-- ---------------------------------------------------------------------
-- Table : fichiers
-- ---------------------------------------------------------------------
CREATE TABLE fichiers (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer      NOT NULL,
    nom_fichier   varchar(255) NOT NULL,
    chemin        varchar(500) NOT NULL,
    visibilite    varchar(20)  NOT NULL DEFAULT 'privee',
    classe        varchar(50),
    taille_octets bigint,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_fichiers_user
        FOREIGN KEY (user_id) REFERENCES users (id_users)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT chk_fichiers_visibilite
        CHECK (visibilite IN ('privee', 'classe', 'publique')),
    CONSTRAINT chk_fichiers_taille
        CHECK (taille_octets IS NULL OR taille_octets >= 0)
);

CREATE INDEX idx_fichiers_user_id    ON fichiers (user_id);
CREATE INDEX idx_fichiers_visibilite ON fichiers (visibilite);

COMMENT ON COLUMN fichiers.visibilite    IS 'privee / classe / publique';
COMMENT ON COLUMN fichiers.taille_octets IS 'Taille en octets (bigint : supporte les fichiers > 2 Go)';

-- ---------------------------------------------------------------------
-- Table : liens
-- ---------------------------------------------------------------------
CREATE TABLE liens (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre       varchar(150) NOT NULL,
    url         varchar(500) NOT NULL,
    description varchar(500),
    ordre       integer     NOT NULL DEFAULT 0,
    created_by  integer,
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_liens_user
        FOREIGN KEY (created_by) REFERENCES users (id_users)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE INDEX idx_liens_ordre ON liens (ordre);

-- ---------------------------------------------------------------------
-- Table : articles
-- ---------------------------------------------------------------------
CREATE TABLE articles (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre        varchar(200) NOT NULL,
    contenu      text,
    image_url    varchar(500),
    mis_en_avant boolean     NOT NULL DEFAULT false,
    auteur_id    integer     NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_articles_auteur
        FOREIGN KEY (auteur_id) REFERENCES users (id_users)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX idx_articles_auteur_id    ON articles (auteur_id);
CREATE INDEX idx_articles_mis_en_avant ON articles (mis_en_avant) WHERE mis_en_avant;

COMMENT ON COLUMN articles.contenu IS 'Contenu de l''article';

-- ---------------------------------------------------------------------
-- Table : galerie_photos
-- ---------------------------------------------------------------------
CREATE TABLE galerie_photos (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre       varchar(150),
    chemin      varchar(500) NOT NULL,
    classe      varchar(50),
    theme       varchar(50),
    uploaded_by integer,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_galerie_user
        FOREIGN KEY (uploaded_by) REFERENCES users (id_users)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE INDEX idx_galerie_uploaded_by ON galerie_photos (uploaded_by);
CREATE INDEX idx_galerie_classe      ON galerie_photos (classe);

-- ---------------------------------------------------------------------
-- Table : logs
-- ---------------------------------------------------------------------
CREATE TABLE logs (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer,
    action     varchar(100) NOT NULL,
    details    varchar(500),
    ip_address inet,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_logs_user
        FOREIGN KEY (user_id) REFERENCES users (id_users)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE INDEX idx_logs_user_id    ON logs (user_id);
CREATE INDEX idx_logs_created_at ON logs (created_at DESC);

COMMENT ON COLUMN logs.ip_address IS 'Type inet : accepte IPv4 et IPv6';

-- ---------------------------------------------------------------------
-- Mise à jour automatique de updated_at
-- ---------------------------------------------------------------------
CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_articles_updated_at
    BEFORE UPDATE ON articles
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_liens_updated_at
    BEFORE UPDATE ON liens
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- Données de base
-- ---------------------------------------------------------------------
INSERT INTO role (nom_role) VALUES
    ('admin'),
    ('professeur'),
    ('etudiant');

COMMIT;
